<!DOCTYPE html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Identity & Directory | CADCOLAB ENFAS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><style>body{background:#0f172a;color:#e2e8f0}.card{background:#111827;border-color:#273244;color:#e2e8f0}.form-control,.form-select{background:#0f172a;color:#e2e8f0;border-color:#334155}.form-control:focus{background:#0f172a;color:#fff}.muted{color:#94a3b8}.code{font-family:monospace;color:#7dd3fc}</style></head><body><div class="container py-4">
<div class="d-flex justify-content-between align-items-center mb-4"><div><div class="text-info fw-bold">CADCOLAB ENFAS IAM</div><h1 class="h3">Identity & Directory</h1><div class="muted">Configuração central do LDAP/Active Directory.</div></div><a class="btn btn-outline-light" href="/dashboard">Voltar</a></div>
@if(session('swal'))<script>Swal.fire({icon:'success',title:'Concluído',text:@json(session('swal'))});</script>@endif
@if(session('swal_error'))<script>Swal.fire({icon:'error',title:'Falha',text:@json(session('swal_error'))});</script>@endif
<div class="card p-4 mb-4"><form method="POST" action="/identity-directory/settings">@csrf
<div class="row g-3"><div class="col-md-6"><label class="form-label">Servidor LDAP/AD</label><input class="form-control" name="host" value="{{ $ldap['host'] }}" required></div><div class="col-md-2"><label class="form-label">Porta</label><input class="form-control" type="number" name="port" value="{{ $ldap['port'] }}" required></div><div class="col-md-2"><label class="form-label">Timeout</label><input class="form-control" type="number" name="timeout" value="{{ $ldap['timeout'] }}" required></div><div class="col-md-2 d-flex align-items-end"><div><div class="form-check"><input class="form-check-input" type="checkbox" name="ssl" value="1" {{ $ldap['ssl']?'checked':'' }}><label class="form-check-label">LDAPS</label></div><div class="form-check"><input class="form-check-input" type="checkbox" name="start_tls" value="1" {{ $ldap['start_tls']?'checked':'' }}><label class="form-check-label">StartTLS</label></div></div></div>
<div class="col-md-4"><label class="form-label">Base DN</label><input class="form-control" name="base_dn" value="{{ $ldap['base_dn'] }}" required></div><div class="col-md-4"><label class="form-label">Users DN / OU</label><input class="form-control" name="users_dn" value="{{ $ldap['users_dn'] }}" required></div><div class="col-md-4"><label class="form-label">Groups DN / OU</label><input class="form-control" name="groups_dn" value="{{ $ldap['groups_dn'] }}" required></div>
<div class="col-md-6"><label class="form-label">Usuário de bind</label><input class="form-control" name="bind_dn" value="{{ $ldap['bind_dn'] }}" required></div><div class="col-md-6"><label class="form-label">Senha de bind {{ $bindPasswordConfigured?'(já configurada)':'' }}</label><input class="form-control" type="password" name="bind_password" placeholder="Deixe em branco para manter a atual"></div><div class="col-md-4"><label class="form-label">Sufixo da conta</label><input class="form-control" name="account_suffix" value="{{ $ldap['account_suffix'] }}" placeholder="@empresa.local"></div><div class="col-md-8"><label class="form-label">Grupos por perfil</label><div class="row g-2"><div class="col"><input class="form-control" name="admin_groups" value="{{ implode(',', $profiles['admin_groups']) }}" placeholder="Admin"></div><div class="col"><input class="form-control" name="ti_groups" value="{{ implode(',', $profiles['ti_groups']) }}" placeholder="TI"></div><div class="col"><input class="form-control" name="rh_groups" value="{{ implode(',', $profiles['rh_groups']) }}" placeholder="RH"></div></div></div>
<div class="col-12"><div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="enabled" value="1" {{ $enabled?'checked':'' }}><label class="form-check-label">Ativar LDAP</label></div><div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="sync_on_login" value="1" {{ $syncOnLogin?'checked':'' }}><label class="form-check-label">Sincronizar ao entrar</label></div><div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="local_fallback" value="1" {{ $localFallback?'checked':'' }}><label class="form-check-label">Fallback local</label></div></div></div>
<div class="mt-3"><button class="btn btn-primary">Salvar configuração</button></div></form></div>
<div class="d-flex gap-2 mb-4"><form method="POST" action="/identity-directory/test">@csrf<button class="btn btn-outline-info">Testar conexão</button></form><form method="POST" action="/identity-directory/sync">@csrf<button class="btn btn-success">Sincronizar agora</button></form><span class="align-self-center {{ $connection['success']?'text-success':'text-warning' }}">{{ $connection['message'] }}</span></div>
<div class="card p-4 mb-4"><h2 class="h5">Usuários sincronizados</h2><div class="table-responsive"><table class="table table-dark table-striped"><thead><tr><th>Usuário</th><th>Nome</th><th>E-mail</th><th>Setor</th><th>Cargo</th><th>Perfil</th><th>Status</th></tr></thead><tbody>@forelse($users as $u)<tr><td class="code">{{ $u->username }}</td><td>{{ $u->display_name }}</td><td>{{ $u->email }}</td><td>{{ $u->department }}</td><td>{{ $u->title }}</td><td>{{ $u->profile }}</td><td>{{ $u->is_active?'Ativo':'Bloqueado' }}</td></tr>@empty<tr><td colspan="7" class="text-center muted">Nenhum usuário sincronizado.</td></tr>@endforelse</tbody></table></div></div>
<div class="card p-4"><h2 class="h5">Grupos</h2><div class="row g-2">@forelse($groups as $g)<div class="col-md-4"><div class="border rounded p-2"><strong>{{ $g->name }}</strong><div class="small muted text-truncate">{{ $g->distinguished_name }}</div></div></div>@empty<div class="muted">Nenhum grupo sincronizado.</div>@endforelse</div></div>
</div></body></html>
