@extends('layouts.cadcolab-v5')
@section('content')
<div class="v5-card">
    <div class="v5-section-head"><div><h2>Colaboradores</h2><small style="color:var(--v5-muted)">Identidade, vínculo, acessos e ciclo de vida em uma única visão.</small></div><form method="GET" action="/dashboard" style="display:flex;gap:8px"><input type="hidden" name="p" value="colaboradores"><input name="busca" value="{{ request('busca') }}" placeholder="Nome, CPF ou matrícula" style="min-width:260px;background:#0f1420;border:1px solid var(--v5-border);color:#fff;border-radius:9px;padding:9px 11px"><button style="border:0;border-radius:9px;background:var(--v5-primary);color:#fff;padding:9px 12px;font-weight:700">Buscar</button></form></div>
</div>
<div class="v5-section" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:14px">
@forelse($dados['colabs'] ?? [] as $c)
    @php $foto=!empty($c['foto_path'])?'/'.ltrim($c['foto_path'],'/'):null; $status=strtolower((string)($c['status']??'pendente')); @endphp
    <article class="v5-card" style="padding:16px">
        <div style="display:flex;gap:13px;align-items:flex-start">
            <div style="width:64px;height:64px;border-radius:14px;overflow:hidden;background:#0d1522;flex:0 0 64px;border:1px solid var(--v5-border)">@if($foto)<img src="{{ $foto }}" alt="" style="width:100%;height:100%;object-fit:cover;object-position:center top">@else<div style="height:100%;display:grid;place-items:center;color:#5f708d"><i class="fa-solid fa-user fa-xl"></i></div>@endif</div>
            <div style="min-width:0;flex:1"><div style="display:flex;justify-content:space-between;gap:10px"><div><strong style="font-size:14px">{{ $c['nome_completo'] ?? 'Sem nome' }}</strong><div style="font-size:10px;color:var(--v5-muted);margin-top:4px">{{ $c['matricula'] ?? 'Sem matrícula' }} • {{ $c['crg'] ?? 'Sem cargo' }}</div></div><span class="v5-badge">{{ strtoupper($status) }}</span></div><div style="margin-top:9px;font-size:11px;color:#bac7da">{{ $c['seto'] ?? 'Sem setor' }} • {{ $c['un'] ?? 'Sem unidade' }}</div><div style="margin-top:5px;font-size:10px;color:var(--v5-muted)">{{ !empty($c['username_criado']) ? $c['username_criado'].'@enfas.com.br' : 'Conta corporativa pendente' }}</div></div>
        </div>
        <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px"><div style="background:#101724;border:1px solid var(--v5-border);border-radius:10px;padding:9px"><small style="color:var(--v5-muted)">Admissão</small><div style="font-size:11px;margin-top:3px">{{ $c['data_admissao_fmt'] ?? '-' }}</div></div><div style="background:#101724;border:1px solid var(--v5-border);border-radius:10px;padding:9px"><small style="color:var(--v5-muted)">Gestor</small><div style="font-size:11px;margin-top:3px">{{ $c['nome_gestor'] ?? '-' }}</div></div><div style="background:#101724;border:1px solid var(--v5-border);border-radius:10px;padding:9px"><small style="color:var(--v5-muted)">Atualização</small><div style="font-size:11px;margin-top:3px">{{ $c['atualizado_fmt'] ?? ($c['criado_fmt'] ?? '-') }}</div></div></div>
        <div style="display:flex;flex-wrap:wrap;gap:7px;margin-top:13px"><a class="v5-badge" style="text-decoration:none" href="/dashboard?p=ficha&id={{ $c['id'] }}"><i class="fa-solid fa-file-lines"></i>&nbsp;Ficha</a><a class="v5-badge" style="text-decoration:none" href="/dashboard?p=cracha&id={{ $c['id'] }}"><i class="fa-solid fa-id-card"></i>&nbsp;Crachá</a><form method="POST" action="/acao">@csrf<input type="hidden" name="action" value="change_status"><input type="hidden" name="id" value="{{ $c['id'] }}"><input type="hidden" name="status" value="{{ $status==='ativo'?'bloqueado':'ativo' }}"><button class="v5-badge" style="border:0;cursor:pointer"><i class="fa-solid {{ $status==='ativo'?'fa-lock':'fa-unlock' }}"></i>&nbsp;{{ $status==='ativo'?'Bloquear':'Ativar' }}</button></form></div>
    </article>
@empty<div class="v5-card" style="grid-column:1/-1;color:var(--v5-muted)">Nenhum colaborador encontrado.</div>@endforelse
</div>
@endsection
