@extends('layouts.cadcolab-v5')
@section('content')
<div class="v5-grid">
    <div class="v5-card"><small style="color:var(--v5-primary);font-weight:800">IDENTIDADE</small><h3 style="margin:8px 0 6px">LDAP / Active Directory</h3><p style="margin:0;color:var(--v5-muted);font-size:11px">Autoridade de identidade, sincronização, grupos e autenticação.</p><a href="#identity" class="v5-badge" style="text-decoration:none;margin-top:12px">Configurar</a></div>
    <div class="v5-card"><small style="color:var(--v5-primary);font-weight:800">MICROSOFT</small><h3 style="margin:8px 0 6px">Microsoft 365</h3><p style="margin:0;color:var(--v5-muted);font-size:11px">Tenant, App Registration, Graph e licenciamento.</p><a href="/dashboard?p=microsoft365" class="v5-badge" style="text-decoration:none;margin-top:12px">Abrir módulo</a></div>
    <div class="v5-card"><small style="color:var(--v5-primary);font-weight:800">GOOGLE</small><h3 style="margin:8px 0 6px">Google Workspace</h3><p style="margin:0;color:var(--v5-muted);font-size:11px">Domínio, service account e provisionamento.</p><a href="/dashboard?p=google-workspace" class="v5-badge" style="text-decoration:none;margin-top:12px">Abrir módulo</a></div>
    <div class="v5-card"><small style="color:var(--v5-primary);font-weight:800">COMUNICAÇÕES</small><h3 style="margin:8px 0 6px">SMTP & WhatsApp</h3><p style="margin:0;color:var(--v5-muted);font-size:11px">Entrega de e-mail, Meta Cloud API e templates.</p><a href="/dashboard?p=comunicacoes" class="v5-badge" style="text-decoration:none;margin-top:12px">Abrir módulo</a></div>
</div>
<div class="v5-section v5-card" id="identity"><div class="v5-section-head"><div><h2>Identidade & Diretório</h2><small style="color:var(--v5-muted)">Configuração segura do LDAP/AD. Senhas existentes não são exibidas.</small></div><div style="display:flex;gap:8px"><form method="POST" action="/enterprise-settings/identity/test">@csrf<button class="v5-badge" style="border:0;cursor:pointer">Testar conexão</button></form><form method="POST" action="/enterprise-settings/identity/sync">@csrf<button class="v5-badge" style="border:0;cursor:pointer">Sincronizar agora</button></form></div></div>
<form method="POST" action="/enterprise-settings/identity" id="identityForm">@csrf
<div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px">
@foreach([['host','Servidor LDAP/AD','text'],['port','Porta','number'],['base_dn','Base DN','text'],['users_dn','Users DN','text'],['groups_dn','Groups DN','text'],['bind_dn','Bind DN','text'],['bind_password','Senha de serviço','password'],['account_suffix','Sufixo da conta','text'],['admin_groups','Grupos Admin','text'],['ti_groups','Grupos TI','text'],['rh_groups','Grupos RH','text'],['timeout','Timeout (s)','number']] as [$name,$label,$type])
<label style="display:flex;flex-direction:column;gap:6px;font-size:10px;color:var(--v5-muted)">{{ $label }}<input name="{{ $name }}" type="{{ $type }}" @if($name==='port') value="389" @elseif($name==='timeout') value="8" @endif style="background:#0f1420;border:1px solid var(--v5-border);color:#fff;border-radius:9px;padding:10px"></label>
@endforeach
</div>
<div style="display:flex;flex-wrap:wrap;gap:14px;margin-top:14px;font-size:11px"><label><input type="checkbox" name="enabled" value="1"> Ativar LDAP</label><label><input type="checkbox" name="sync_on_login" value="1"> Sincronizar no login</label><label><input type="checkbox" name="local_fallback" value="1"> Fallback local</label><label><input type="checkbox" name="ssl" value="1"> LDAPS</label><label><input type="checkbox" name="start_tls" value="1"> StartTLS</label></div>
<button style="margin-top:15px;border:0;border-radius:10px;background:var(--v5-primary);color:#fff;padding:10px 15px;font-weight:800;cursor:pointer">Salvar Identidade</button>
</form></div>
@push('scripts')<script>fetch('/enterprise-settings/identity',{headers:{Accept:'application/json'},credentials:'same-origin'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{const f=document.getElementById('identityForm');if(!f)return;const map={host:d.ldap?.host,port:d.ldap?.port,base_dn:d.ldap?.base_dn,users_dn:d.ldap?.users_dn,groups_dn:d.ldap?.groups_dn,bind_dn:d.ldap?.bind_dn,account_suffix:d.ldap?.account_suffix,admin_groups:d.profiles?.admin_groups,ti_groups:d.profiles?.ti_groups,rh_groups:d.profiles?.rh_groups,timeout:d.ldap?.timeout};Object.entries(map).forEach(([k,v])=>{if(f.elements[k]&&v!==undefined&&v!==null)f.elements[k].value=v});['enabled','sync_on_login','local_fallback'].forEach(k=>{if(f.elements[k])f.elements[k].checked=!!d[k]});if(f.elements.ssl)f.elements.ssl.checked=!!d.ldap?.ssl;if(f.elements.start_tls)f.elements.start_tls.checked=!!d.ldap?.start_tls}).catch(()=>{});</script>@endpush
@endsection
